version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    working_dir: /app
    tty: true
    command: sh -c "cd todo-app && yarn install && yarn serve"
